name: GitHub Metrics
on:
  schedule:
    - cron: "0 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:  # Permet le déclenchement manuel
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options de base
          user: vitalfocheux
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugin languages
          plugin_languages: yes
          plugin_languages_indepth: yes  # Analyse approfondie
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 2%  # Ignore les langages < 2%
          plugin_languages_other: yes  # Groupe "Other" pour les petits langages
          plugin_languages_ignored: html, css  # Langages à ignorer
